name: update-package-index
on:
  push:
    branches: [ "main" ]
    paths:
      - 'deb/**.deb'

  workflow_dispatch:
jobs:
  update-repo-index:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Update Package Index
        run: |
          sudo apt install -y apt-utils dpkg-dev
          dpkg-scanpackages . /dev/null > Packages
          gzip -k -f Packages
          apt-ftparchive release . > Release

      - name: Commit Updated Index
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updating Package Index"
          file_pattern: 'debian_repo/Packages* debian_repo/Release'
